### ISSUE TITLE
Hard coded flags web path ?

### ISSUE THREAD

**Issue by EmmanuelVella** [servergrove/ServerGroveLocaleBundle#19]
Hi,

If I well understand, I need to download my flags images in a custom directory. But why is the web path `/images/locale` hard coded ?

Thanks for you help ;)

**Comment by pgodel** [comment]
the files should get copied by

```
app/console assets:install
```

**Comment by EmmanuelVella** [comment]
Thanks for your response. When I execute the assets:install command, the bundle assets are indeed installed : 

`Installing assets for ServerGrove\LocaleBundle into web/bundles/servergrovelocale`

But still no `/images/locale` directory !

**Comment by pgodel** [comment]
@iambrosi do you recall the details?

**Comment by iambrosi** [comment]
@pgodel Images are installed by assetic, not by the classic command `assets:install`. @EmmanuelVella You just need to run `assetic:dump` to export the flags into the web dir. I think is possible to implement an option for a custom path inside the web dir.

**Comment by EmmanuelVella** [comment]
Thanks, I will test asap and give you a feedback.

**Comment by EmmanuelVella** [comment]
It's ok, thank you very much for your help.
